### ISSUE TITLE
Unable to start mopidy tornado dependency error

### ISSUE THREAD

**Issue by skluthe** [mopidy/homebrew-mopidy#22]
Hey, I was originally getting this error after following the official mopidy macos install:

```
Traceback (most recent call last):
File “/usr/local/bin/mopidy”, line 5, in 
from pkg_resources import load_entry_point
File “/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/init.py”, line 3095, in 
@_call_aside
File “/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/init.py”, line 3081, in _call_aside
f(*args, **kwargs)
File “/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/init.py”, line 3108, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File “/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/init.py”, line 658, in _build_master
ws.require(requires)
File “/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/init.py”, line 959, in require
needed = self.resolve(parse_requirements(requirements))
File “/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/init.py”, line 846, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The ‘Mopidy==2.1.0’ distribution was not found and is required by the application
```
But adding the provided path info into my bash_profile seems to have fixed it. Now I'm getting this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 885, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tornado>=3.2' distribution was not found and is required by Mopidy
```
I have the latest version of tornado installed but still get this error. Any ideas?

**Comment by skluthe** [comment]
I'm running the latest macos version.

**Comment by skluthe** [comment]
Solution: manually install the tornado, cffi, requests and pykka to get this to work via pip install

**Comment by troyxmccall** [comment]
@skluthe did you have any issues with Gstreamer in addition? I ran into this issue after pip installing tornado, cffi, requests and pykka.

```
$ mopidy

ERROR: A GObject Python package was not found.

Mopidy requires GStreamer to work. GStreamer is a C library with a
number of dependencies itself, and cannot be installed with the regular
Python tools like pip.

Please see http://docs.mopidy.com/en/latest/installation/ for
instructions on how to install the required dependencies.

Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy==2.1.0', 'console_scripts', 'mopidy')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/site-packages/mopidy/__main__.py", line 8, in <module>
    from mopidy.internal.gi import Gst  # noqa: F401
  File "/usr/local/lib/python2.7/site-packages/mopidy/internal/gi.py", line 8, in <module>
    import gi
  File "/usr/local/lib/python2.7/site-packages/gi/__init__.py", line 42, in <module>
ImportError: cannot import name _gi
```

**Comment by simmel** [comment]
I don't think it's related to this issue at all @troyxmccall but I did have the same problem. Not sure if you're on OS X but after I uninstalled everything and re-installed mopidy (and thus all the dependencies) with `brew uninstall --ignore-dependencies gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-python mopidy && brew install mopidy`

**Comment by jodal** [comment]
@troyxmccall I ran into your issue as well today, where the `_gi` module cannot be imported. It looks like the proper solution is to reinstall pyobject3 for Python 2 support by running:

```
brew reinstall pygobject3 --with-python@2
```

Afterwards, `brew test pygobject3` should output:

```
Testing pygobject3
==> python3 test.py
==> python2.7 test.py
```

**Comment by jodal** [comment]
The formulas have now been modernized and rewritten to keep their dependencies in their own `libexec` dirs. Thus, I'm closing this issue as outdated. Please open a new issue if you are still experiencing issues after a `brew upgrade`.
