### ISSUE TITLE
Mopidy fails to install on OSX

### ISSUE THREAD

**Issue by stormtroopa** [mopidy/homebrew-mopidy#37]
Hi! I hope smd. might help me with the installation.
I am trying to install mopidy on a fresh OSX 10.15.5.

I followed the installation guide on: https://docs.mopidy.com/en/latest/installation/macos/#install-from-homebrew

But sadly it fails. Please see the output below. Any idea what might cause the problem?

```
==> Installing mopidy from mopidy/mopidy
==> Downloading https://files.pythonhosted.org/packages/41/bf/9d214a5af07debc6acf7f3f257265618f1db242a3f8e4
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/538805ce4e70bd462e8d2c9a769c02994d647d9a1ba7c1ede9e368ac54f2aa09--certifi-2019.11.28.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/de28644dd0ba2aaf30228e9b28ba90366e333e7a34e1b1f97cf85d0edd0cb278--chardet-3.0.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03e
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/b3673db65852656b6c4f3e1dbb5c5528f2a4e12a92dba9ca1950f133a076ff63--idna-2.8.tar.gz
==> Downloading https://files.pythonhosted.org/packages/8c/25/26af8b333bbc6b00bd03a95c058c50e6161af50680030
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/98820d1258c4a4b2d097b5fcfd1ee709496f32f746b0b451d7f424a8a2d9d2a3--Pykka-2.0.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/01/62/ddcf76d1d19885e8579acb1b1df26a852b03472c0e46d
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/31866dbbc0d1d714cefca0451e581434adefbb4422be33aa33f82f0fbcca647c--requests-2.22.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/30/78/2d2823598496127b21423baffaa186b668f73cd91887f
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/b5654e5a66adf4d7c09370dcf6fdc046456b93395376919fa7d52a312f2a69c4--tornado-6.0.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ad/fc/54d62fa4fc6e675678f9519e677dfc29b8964278d7533
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/93e0db8b690e2cf676677b0484407e6d7762ebff88d7ff43dfd137fe431373f3--urllib3-1.25.7.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b0/6f/eaadbe67c5b99215bfa247257fc20cb997674f5ecf376
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/84399e958e4160b57a651b2e909fa01e50a56609415635b540b9681da6532b2f--Mopidy-3.0.2.tar.gz
==> /usr/local/opt/python@3.8/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local
Last 15 lines from /Users/user/Library/Logs/Homebrew/mopidy/01.python3:
2020-07-17 17:55:07 +0200

/usr/local/opt/python@3.8/bin/python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/mopidy/3.0.2_1/libexec
--install-scripts=/usr/local/Cellar/mopidy/3.0.2_1/libexec/bin
--single-version-externally-managed
--record=installed.txt


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/mopidy/homebrew-mopidy/issues
```

**Comment by jodal** [comment]
Can you provide the full contents of the file `/Users/user/Library/Logs/Homebrew/mopidy/01.python3`?

**Comment by stormtroopa** [comment]
```
/usr/local/opt/python@3.8/bin/python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/mopidy/3.0.2_1/libexec
--install-scripts=/usr/local/Cellar/mopidy/3.0.2_1/libexec/bin
--single-version-externally-managed
--record=installed.txt


HOMEBREW_VERSION: 2.4.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 13f0d4ad2b0773c01c5fdd5f8cba3e4f312c1c96
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8402a1b35d1f1f551413fb414d5bdc67011a0e34
Core tap last commit: 37 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 2
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/libffi:/usr/local/opt/icu4c:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python@3.8/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.8/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/gstreamer/lib/pkgconfig:/usr/local/opt/libogg/lib/pkgconfig:/usr/local/opt/libvorbis/lib/pkgconfig:/usr/local/opt/opus/lib/pkgconfig:/usr/local/opt/orc/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/lzo/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/fribidi/lib/pkgconfig:/usr/local/opt/graphite2/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig:/usr/local/opt/pango/lib/pkgconfig:/usr/local/opt/theora/lib/pkgconfig:/usr/local/opt/gst-plugins-base/lib/pkgconfig:/usr/local/opt/flac/lib/pkgconfig:/usr/local/opt/atk/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/gdk-pixbuf/lib/pkgconfig:/usr/local/opt/libepoxy/lib/pkgconfig:/usr/local/opt/gtk+3/lib/pkgconfig:/usr/local/opt/speex/lib/pkgconfig:/usr/local/opt/libshout/lib/pkgconfig:/usr/local/opt/gmp/lib/pkgconfig:/usr/local/opt/libidn2/lib/pkgconfig:/usr/local/opt/libtasn1/lib/pkgconfig:/usr/local/opt/nettle/lib/pkgconfig:/usr/local/opt/p11-kit/lib/pkgconfig:/usr/local/opt/libevent/lib/pkgconfig:/usr/local/opt/unbound/lib/pkgconfig:/usr/local/opt/gnutls/lib/pkgconfig:/usr/local/opt/libpsl/lib/pkgconfig:/usr/local/opt/webp/lib/pkgconfig:/usr/local/opt/gd/lib/pkgconfig:/usr/local/opt/jasper/lib/pkgconfig:/usr/local/opt/netpbm/lib/pkgconfig:/usr/local/opt/gts/lib/pkgconfig:/usr/local/opt/graphviz/lib/pkgconfig:/usr/local/opt/vala/lib/pkgconfig:/usr/local/opt/libsoup/lib/pkgconfig:/usr/local/opt/libvpx/lib/pkgconfig:/usr/local/opt/taglib/lib/pkgconfig:/usr/local/opt/libmms/lib/pkgconfig:/usr/local/opt/libnice/lib/pkgconfig:/usr/local/opt/rtmpdump/lib/pkgconfig:/usr/local/opt/srtp/lib/pkgconfig:/usr/local/opt/gst-plugins-bad/lib/pkgconfig:/usr/local/opt/x264/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/py3cairo/lib/pkgconfig:/usr/local/opt/pygobject3/lib/pkgconfig:/usr/local/opt/gsettings-desktop-schemas/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python@3.8/bin:/usr/local/opt/gettext/bin:/usr/local/opt/pcre/bin:/usr/local/opt/glib/bin:/usr/local/opt/gstreamer/bin:/usr/local/opt/orc/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/fontconfig/bin:/usr/local/opt/cairo/bin:/usr/local/opt/fribidi/bin:/usr/local/opt/graphite2/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/harfbuzz/bin:/usr/local/opt/pango/bin:/usr/local/opt/gst-plugins-base/bin:/usr/local/opt/flac/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/gdk-pixbuf/bin:/usr/local/opt/gtk+3/bin:/usr/local/opt/lame/bin:/usr/local/opt/libidn2/bin:/usr/local/opt/libtasn1/bin:/usr/local/opt/nettle/bin:/usr/local/opt/p11-kit/bin:/usr/local/opt/libevent/bin:/usr/local/opt/gnutls/bin:/usr/local/opt/libpsl/bin:/usr/local/opt/webp/bin:/usr/local/opt/gd/bin:/usr/local/opt/jasper/bin:/usr/local/opt/netpbm/bin:/usr/local/opt/gts/bin:/usr/local/opt/libtool/bin:/usr/local/opt/graphviz/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/vala/bin:/usr/local/opt/taglib/bin:/usr/local/opt/faac/bin:/usr/local/opt/faad2/bin:/usr/local/opt/libnice/bin:/usr/local/opt/musepack/bin:/usr/local/opt/rtmpdump/bin:/usr/local/opt/x264/bin:/usr/local/opt/gobject-introspection/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by stormtroopa** [comment]
I managed to install mopidy on my other MAC. There was another problem which could be solved by installing python-object manually.
The mopidy installation was successful but it didn't start:


```
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 33, in <module>
    sys.exit(load_entry_point('Mopidy==3.0.2', 'console_scripts', 'mopidy')())
  File "/usr/local/bin/mopidy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/mopidy/3.0.2_1/libexec/lib/python3.8/site-packages/mopidy/__main__.py", line 7, in <module>
    from mopidy import commands
  File "/usr/local/Cellar/mopidy/3.0.2_1/libexec/lib/python3.8/site-packages/mopidy/commands.py", line 15, in <module>
    from mopidy.audio import Audio
  File "/usr/local/Cellar/mopidy/3.0.2_1/libexec/lib/python3.8/site-packages/mopidy/audio/__init__.py", line 2, in <module>
    from .actor import Audio
  File "/usr/local/Cellar/mopidy/3.0.2_1/libexec/lib/python3.8/site-packages/mopidy/audio/actor.py", line 8, in <module>
    from mopidy.audio import tags as tags_lib
  File "/usr/local/Cellar/mopidy/3.0.2_1/libexec/lib/python3.8/site-packages/mopidy/audio/tags.py", line 7, in <module>
    from mopidy.internal.gi import GLib, Gst
  File "/usr/local/Cellar/mopidy/3.0.2_1/libexec/lib/python3.8/site-packages/mopidy/internal/gi.py", line 7, in <module>
    gi.require_version("Gst", "1.0")
AttributeError: module 'gi' has no attribute 'require_version'
```

I had to run `pip3 install PyGObject` afterwards to get mopidy running

**Comment by dmorais0** [comment]
I'm seeing the same problem.  I'm using Mac OS 10.14.6.
```
==> /usr/local/opt/python@3.8/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/mopidy/3.0.2_1/
Last 15 lines from /Users/dmorais/Library/Logs/Homebrew/mopidy/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/mopidy/3.0.2_1/libexec
--install-scripts=/usr/local/Cellar/mopidy/3.0.2_1/libexec/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/mopidy/homebrew-mopidy/issues

These open issues may also help:
Mopidy fails to install on OSX https://github.com/mopidy/homebrew-mopidy/issues/37
```

Any idea how to get past this?

**Comment by dmorais0** [comment]
@paulproteus solved this issue for me by suggesting I simply run:
- /usr/local/opt/python@3.8/bin/python3 -m ensurepip
-  /usr/local/opt/python@3.8/bin/python3 -m pip install -U setuptools

And now mopidy appears to be installed :-).

**Comment by rynjms** [comment]
FWIW, none of the other suggested solutions in this issue worked for me on Monterey with a fresh install of Homebrew.

It appears that Homebrew's Python 3.9 omits the symlink named `python3` in `/usr/local/opt/python@3.9/bin`. I did a `brew postinstall python@3.9` but it didn't add it. (Maybe it's just inconsistent between Python versions -- 3.10 has it, and it looks like from the previous comment 3.8 does.)

The solution was to `brew edit mopidy` and change the line:

```
    python3 = Formula["python@3.9"].opt_bin/"python3"
```

to:

```
    python3 = Formula["python@3.9"].opt_bin/"python3.9"
```

Then a `brew install mopidy` completed successfully for me.

**Comment by tiefenauer** [comment]
I had the same issue and @rynjms ' solution worked for me

**Comment by jodal** [comment]
I'm not certain that the issues described here in 2020 and 2022 have the same root causes, but all the formulas in this tap has now been updated to use Python 3.11 instead of 3.9 and use the explicit Python version described by @rynjms above.

They all seem to work with the latest Homebrew on macOS 12.6.3, which is the latest macOS I can install on the only Mac I have available these days.

Please open new issues if you run into any problems.
