### ISSUE TITLE
Unable to run on Mac OS 

### ISSUE THREAD

**Issue by steveof2620** [mopidy/homebrew-mopidy#39]
Hello,

I installed with Mopidy via Brew and later installed a few plugs. 

When trying to run Mopidy I see the following error:
```

ERROR: A GObject based library was not found.

Mopidy requires GStreamer to work. GStreamer is a C library with a
number of dependencies itself, and cannot be installed with the regular
Python tools like pip.

Please see https://docs.mopidy.com/en/latest/installation/ for
instructions on how to install the required dependencies.

Traceback (most recent call last):
  File "/Users/stevencurren/miniconda3/bin/mopidy", line 5, in <module>
    from mopidy.__main__ import main
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/mopidy/__main__.py", line 7, in <module>
    from mopidy import commands
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/mopidy/commands.py", line 15, in <module>
    from mopidy.audio import Audio
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/mopidy/audio/__init__.py", line 2, in <module>
    from .actor import Audio
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/mopidy/audio/actor.py", line 8, in <module>
    from mopidy.audio import tags as tags_lib
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/mopidy/audio/tags.py", line 7, in <module>
    from mopidy.internal.gi import GLib, Gst
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/mopidy/internal/gi.py", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

```

Have also tried >> brew reinstall gstreamer

Mac OS >> 10.15.7

Thanks.

**Comment by jodal** [comment]
I'm not very familiar with miniconda3, but from the paths I see that Mopidy is installed using miniconda3's Python, and not the Python from Homebrew. Will Mopidy running under that Python installation have access to the `gi` module installed by Homebrew under the Homebrew Python installation?

I'd uninstall Mopidy under miniconda3:

```
/Users/stevencurren/miniconda3/bin/python -m pip uninstall mopidy
```

Then install it again using the Homebrew Python:

```
$(brew --prefix)/bin/python -m pip install mopidy
```

...and do the same for any Mopidy extensions installed under miniconda3.

**Comment by steveof2620** [comment]
Thanks,

I ran the command /Users/stevencurren/miniconda3/bin/python -m pip uninstall mopidy,

had the following errors:

Proceed (y/n)? y
```
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/stevencurren/miniconda3/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/Users/stevencurren/miniconda3/lib/python3.8/site-packages/Mopidy-3.1.1.dist-info/' -> '/Users/stevencurren/miniconda3/lib/python3.8/site-packages/~opidy-3.1.1.dist-info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/pip/_internal/commands/uninstall.py", line 89, in run
    uninstall_pathset = req.uninstall(
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 686, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 394, in remove
    moved.stash(path)
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 283, in stash
    renames(path, new_path)
  File "/Users/stevencurren/miniconda3/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 352, in renames
    shutil.move(old, new)
  File "/Users/stevencurren/miniconda3/lib/python3.8/shutil.py", line 800, in move
    rmtree(src)
  File "/Users/stevencurren/miniconda3/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/Users/stevencurren/miniconda3/lib/python3.8/shutil.py", line 672, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/Users/stevencurren/miniconda3/lib/python3.8/shutil.py", line 670, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'RECORD'

```
I just removed the entire miniconda3 directory. Not sure about my set up TBO.

I uninstalled and reinstalled and now it's running. Thanks.

**Comment by jodal** [comment]
Awesome :-)
